system_logger:
  system_logger_logging_level: debug
  system_logger_destination: stdout
  system_logger_format: text

pip:
  listen_addr: "pip.ztsfc.com:443"
  certs_pip_accepts_when_shown_by_pdp:
    - ./certs/bwnet_root.crt
  cert_shown_by_pip_to_pdp: ./certs/ztsfc_http_pip.crt
  privkey_for_cert_shown_by_pip_to_pdp: ./certs/ztsfc_http_pip_priv.key

threat_intelligence:
  listen_addr: "pip.ztsfc.com:8080"
  
